name: testing-travis-migration
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        py: [ 3.6 ]

    steps:
        - uses: actions/checkout@v2

        - name: Set up Python ${{ matrix.py }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.py }}

        - name: Check cmake
          run: cmake --version

        - name: Install dependencies
          run: |
            python -m pip install -U pip
            pip install -U numpy

        - name: Build CCL
          run: |
            python setup.py build
            python setup.py develop

        - name: Unit tests
          run: OMP_NUM_THREADS=2 pytest -vv pyccl --cov=pyccl

        - name: Benchmarks
          run: OMP_NUM_THREADS=2 pytest -vv benchmarks --cov=pyccl --cov-append
